name: Build and Push Docker to ECR

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set environment variables
        run: |
          COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

          ECR_IMAGE_NAME=huggingface/cuda_environment
          echo "ECR_IMAGE_NAME=$ECR_IMAGE_NAME" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_IMAGE_NAME }}:${{ env.COMMIT_SHA }} -t ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_IMAGE_NAME }}:${{ env.COMMIT_SHA }}
          docker push ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_IMAGE_NAME }}:latest
